fieldLayouts:
  c36d7a7c-1aa7-46de-ba18-76feaa80e7ef:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-21T18:45:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 3d6256a4-99cf-48ae-a25a-fc453522084b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cc91e4d2-6a39-4f8d-a9f6-1a91142a12ce
        userCondition: null
handle: blog
name: Blog
