color: null
fieldLayouts:
  015d0b52-6211-4ad7-811e-a7b48b1334d9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-21T18:45:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: caff5bac-f2d2-44d2-902f-566c4bf6cff9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: aacd087b-6713-4da5-b63b-ac9c5e55439f
        userCondition: null
handle: footerNav
hasTitleField: false
icon: null
name: 'Footer Nav'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
