color: null
fieldLayouts:
  9532152b-60d8-4b36-8880-ba8fc0a92981:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-23T02:35:55+00:00'
            elementCondition: null
            fieldUid: f2026438-eaa5-4ed8-9aaf-7d211fb068f9 # Plain Text
            handle: null
            includeInCards: false
            instructions: null
            label: Subheading
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 207e6f1a-7f28-42d6-b9f7-f32f3c20cc2b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-23T02:35:55+00:00'
            elementCondition: null
            fieldUid: f97a975b-e641-4b69-937a-8f60b1bf09d7 # Copy Simple
            handle: null
            includeInCards: false
            instructions: null
            label: Copy
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1bb820c5-2119-4e64-870b-c92d977eda6e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-23T02:39:13+00:00'
            elementCondition: null
            fieldUid: 25c500e9-b073-4438-aeae-9897b587a228 # Image(s)
            handle: gallery
            includeInCards: false
            instructions: null
            label: Gallery
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1daeacd5-242e-4022-bda8-5190dae870e7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-23T02:39:13+00:00'
            elementCondition: null
            fieldUid: 79f43a2d-faed-48be-a62a-13d9eef0694f # Address
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 38634a64-01d1-4f4b-9cff-61e96502aec4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3eb0bd95-2b06-4720-90d2-e88cc818d991
        userCondition: null
handle: home
hasTitleField: false
icon: null
name: Home
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
