color: null
fieldLayouts:
  ea7895fd-16b3-41e1-8b80-b25b4a3250e3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-21T18:45:50+00:00'
            elementCondition: null
            heading: Banner
            type: craft\fieldlayoutelements\Heading
            uid: ce9685c5-a85b-4cda-8487-e194abb8953e
            userCondition: null
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-21T18:45:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a239a27c-1be7-434b-a174-487c671213de
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-21T18:45:50+00:00'
            elementCondition: null
            heading: 'Page Blocks'
            type: craft\fieldlayoutelements\Heading
            uid: dd6dcc10-9e69-45e8-9303-a34c12964662
            userCondition: null
        name: Content
        uid: afd3079c-c855-4e99-8057-7c6c582f31b7
        userCondition: null
handle: pages_default
hasTitleField: true
icon: null
name: 'Page(s) - Default'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
