color: null
fieldLayouts:
  baa143cf-3f8f-4ec0-ac5d-463f5ed72b2a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-21T18:45:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7692baae-393f-4f6e-9742-d8a5ee4aea2c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 63c8a659-08c4-42b5-a1c7-2ebff22a833e
        userCondition: null
handle: work_default
hasTitleField: true
icon: null
name: 'Work - Default'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
