columnSuffix: djghqsof
handle: copy
instructions: null
name: Copy
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: 18082357-0ece-4e4d-b895-2b8a9d990349 # Longform
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
