defaultPlacement: end
enableVersioning: true
entryTypes:
  - 2b9d5f8e-8d8c-4588-a681-dcb4e6f97a2a # Default
handle: blog
maxAuthors: 1
name: Blog
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  2033dd80-8be0-4716-ba1a-9accdd5acd0e: # English
    enabledByDefault: true
    hasUrls: true
    template: blog/_entry
    uriFormat: 'blog/{slug}'
type: channel
