defaultPlacement: end
enableVersioning: true
entryTypes:
  - 2be069d2-09e5-4ce2-ab1d-264f09be9f73
handle: blogIndex
maxAuthors: 1
name: 'Blog Index'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  2033dd80-8be0-4716-ba1a-9accdd5acd0e: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: blog/index
    uriFormat: blog
type: single
