defaultPlacement: end
enableVersioning: true
entryTypes:
  - 01a0c18d-3d43-40d2-865f-69907b5d8a80 # FAQs
handle: faqs
maxAuthors: 1
name: FAQs
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  2033dd80-8be0-4716-ba1a-9accdd5acd0e: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: faqs/_entry.twig
    uriFormat: faqs
type: single
