defaultPlacement: end
enableVersioning: true
entryTypes:
  - 08fa341a-ce10-426d-b4ec-9df5d3250bb8 # Home
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  2033dd80-8be0-4716-ba1a-9accdd5acd0e: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: home
    uriFormat: __home__
type: single
