defaultPlacement: end
enableVersioning: true
entryTypes:
  - 07a76d4d-2158-4ef4-8bc1-a615aa9f4e5a # Main Nav
handle: mainNav
maxAuthors: 1
name: 'Main Nav'
propagationMethod: all
siteSettings:
  2033dd80-8be0-4716-ba1a-9accdd5acd0e: # English
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
