defaultPlacement: end
enableVersioning: true
entryTypes:
  - a450ec90-be0a-4ea4-86fa-09497eda060f # Page(s) - Default
handle: pages
maxAuthors: 1
name: Page(s)
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  2033dd80-8be0-4716-ba1a-9accdd5acd0e: # English
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: 2
  uid: 1334abb2-2436-472e-bc0d-c50e6337a4bb
type: structure
